[package]
name = "yew-snake-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
gloo-timers = "0.2.6"
getrandom = { version = "0.2.7", features = ["js"] }
rand = "0.8.5"
